### ISSUE TITLE
Verify network binding setup

### ISSUE THREAD

**Issue by ne0fhyk** [dronekit/dronekit-android#411]
Ensure that the sockets used in the library are  bound to the right network.

**Comment by ne0fhyk** [comment]
@chaviw any updates on the status for this issue?

**Comment by chaviw** [comment]
I started working on it. I realized it might a bit more complex in this case because I need to make sure it's the right network it's binding to. Basically, any sockets that are opened need to know what network. Either the caller tells them or some static method in wifi manager can handle that.

Let me take a look at this week and see how much effort it might be

**Comment by ne0fhyk** [comment]
@chaviw, brainstorming this, the network binding occurs before any connection is established. 
As such by the time network connections start being made, the network should already be available (if needed). So we can either pass it through the connections' constructors or define another `openConnection(Network network)` abstract method to complement the current `openConnection()` method.

**Comment by ne0fhyk** [comment]
Fixed by pr #433
